parameters:
  name: ''
  pool: ''
  platform: ''

jobs:
  - job: ${{ parameters.name }}
    pool: ${{ parameters.pool }}
    steps:
      - bash: |
          echo '##vso[task.setvariable variable=isTag;]true'
        condition: and(succeeded(), startsWith(variables['Build.SourceBranch'], 'refs/tags/'))

      - bash: |
          echo '##vso[task.setvariable variable=isSnapshot;]true'
        condition: and(succeeded(), endsWith(variables['Build.SourceBranch'], '-SNAPSHOT'))

      - ${{ if eq(parameters.platform, 'win') }}:
          - powershell: |
              choco install zulu12
              New-Item 'HKLM:\SOFTWARE\JavaSoft\Java Development Kit\1.12' -Force | New-ItemProperty -Name JavaHome -Value "C:\Program Files\Zulu\zulu-12" -Force

      - task: Gradle@2
        condition: succeeded()
        env:
          GPG_KEY_NAME: $(gpg.keyname)
          GPG_PASSPHRASE: $(gpg.passphrase)
          BINJR_BUILD_NUMBER: $(Build.BuildNumber)
          IS_TAG: $(isTag)
          REPO_TAG_NAME: $(Build.SourceBranchName)
        inputs:
          options: '--parallel'
          gradleWrapperFile: 'gradlew'
          javaHomeOption: 'JDKVersion'
          jdkVersionOption: '1.12'
          jdkArchitectureOption: 'x64'
          publishJUnitResults: false
          tasks: 'signPackageDistribution'

      - task: GithubRelease@0
        condition: and(succeeded(), startsWith(variables['Build.SourceBranch'], 'refs/tags/'))
        inputs:
          gitHubConnection: gh_release
          repositoryName: binjr/binjr
          action: edit
          tag: $(Build.SourceBranchName)
          assets: |
            $(System.DefaultWorkingDirectory)/build/*.msi
            $(System.DefaultWorkingDirectory)/build/*.asc
            $(System.DefaultWorkingDirectory)/build/*.tar.gz
          assetUploadMode: 'replace'
          releaseNotesSource: 'file'
          releaseNotesFile: $(System.DefaultWorkingDirectory)/UNRELEASED.md
          addChangeLog: false
          isPreRelease: $(isSnapshot)