parameters:
  name: ''
  pool: ''
  platform: ''

jobs:
- job: ${{ parameters.name }}
  pool: ${{ parameters.pool }}
  steps:
    - bash: |
        echo '##vso[task.setvariable variable=isTag;]true'
      condition: and(succeeded(), startsWith(variables['Build.SourceBranch'], 'refs/tags/'))

    - task: Gradle@2
      env:
        IS_TAG: $(isTag)
        REPO_TAG_NAME: $(Build.SourceBranchName)
      inputs:
        options: '--parallel'
        gradleWrapperFile: 'gradlew'
        javaHomeOption: 'JDKVersion'
        jdkVersionOption: '1.11'
        jdkArchitectureOption: 'x64'
        publishJUnitResults: false
        tasks: 'packageDistribution'

    - task: GithubRelease@0
      condition: and(succeeded(), startsWith(variables['Build.SourceBranch'], 'refs/tags/'))
      inputs:
        githubConnection: gh_release
        repositoryName: binjr/binjr
        action: edit
        tag: $(Build.SourceBranchName)
        assets: |
          $(System.DefaultWorkingDirectory)/build/*.msi
          $(System.DefaultWorkingDirectory)/build/*.tar.gz
        assetUploadMode: 'replace'
        releaseNotesSource: 'file'
        releaseNotesFile: $(System.DefaultWorkingDirectory)/UNRELEASED.md
        addChangeLog: false