#!/bin/sh

# resolve links - $0 may be a softlink
PRG="$0"

while [ -h "$PRG" ]; do
  ls=`ls -ld "$PRG"`
  link=`expr "$ls" : '.*-> \(.*\)$'`
  if expr "$link" : '/.*' > /dev/null; then
    PRG="$link"
  else
    PRG=`dirname "$PRG"`/"$link"
  fi
done

PRGDIR=`dirname "$PRG"`
BASEDIR=`cd "$PRGDIR/.." >/dev/null; pwd`

JAVACMD="./runtime/bin/java"

exec $JAVACMD \
  -Djdk.gtk.version=2 \
  -splash:"./resources/images/splashscreen.png" \
  -cp "./app/*:./plugins/*" \
  -Dapp.name="binjr" \
  -Dapp.pid="$$" \
  -Dapp.home="$BASEDIR" \
  -Dbasedir="$BASEDIR" \
  "eu.fthevenet.binjr.Binjr" \
  "$@"